export const USER_LOGGED_IN  = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const USER_REGISTERED = "USER_REGISTERED";
export const ALL_TRANSACTIONS = "ALL_TRANSACTIONS";
